### PR TITLE
QuickSort Algorithm

### PR DESCRIPTION
**Pull request by Pumang18**

### CODE REVIEW

**Comment by yashjawale** [comment]
Review File name guidelines in [CONTRIBUTING.md](https://github.com/acesdit/snippets/blob/main/CONTRIBUTING.md#-file-names)

Rename the file.
Then Commit -> Push
It'll update here automatically

Let me know if facing any issues

**Comment by yashjawale** [comment]
And only one file per PR 😅
Utilize branches for simultaneous PRs

**Comment by Pumang18** [comment]
> Review File name guidelines in [CONTRIBUTING.md](https://github.com/acesdit/snippets/blob/main/CONTRIBUTING.md#-file-names)
> 
> Rename the file. Then Commit -> Push It'll update here automatically
> 
> Let me know if facing any issues

Do I need to do PR again after changing name?

**Comment by yashjawale** [comment]
> > Review File name guidelines in [CONTRIBUTING.md](https://github.com/acesdit/snippets/blob/main/CONTRIBUTING.md#-file-names)
> > Rename the file. Then Commit -> Push It'll update here automatically
> > Let me know if facing any issues
> 
> Do I need to do PR again after changing name?

No you don't

**Comment by yashjawale** [comment]
Just create another request for the second file

**Pull request merged**
