### PR TITLE
Added filter based on language

### LINKED ISSUE #8: Add language filtering
Add language filtering to allow users to filter the cards based on their language preference.
Source code already contains partial implementation code in it.

### PR DESCRIPTION
**Pull request by nnisarggada**
Added filtering snippets based on `Language`. Implementation is similar to filtering by `Category`

Fixes #8

### CODE REVIEW

**Comment by yashjawale** [comment]
Is there any way to make language based filtering work in conjunction with Categories...
Like `Data Structures` -> `Java`

Though it raises the complexity level
Like it also does mean that it has to be disabled in case of `Bash`, `AppScript`, etc since they only use a single language

**Comment by yashjawale** [comment]
What are your thoughts on this...?

**Comment by nnisarggada** [comment]
> What are your thoughts on this...?

We can do that. We'll have to use query (search) params in order to do that instead of routes. All the code for the filtering will have to be changed for it

**Comment by yashjawale** [comment]
But then will it still work with SSG...?

**Comment by nnisarggada** [comment]
> But then will it still work with SSG...?

No. `Search Params` would require SSR. 

An alternative would be adding the category and language to the classlist of each card and the use the buttons to hide all cards with the classes selected. 

I'd be happy to help out with any of the mention solutions, you can merge this PR and I will create a new one.

**Comment by yashjawale** [comment]
Yes
Or using a combination of both, routes for categories & client side filtering for languages...
This way the number of cards will be somewhat reduced for filtering

**Comment by yashjawale** [comment]
> I'd be happy to help out with any of the mention solutions, you can merge this PR and I will create a new one.

Yes, I'll merge this one & create another issue

**Pull request merged**
