### PR TITLE
 Password generator .py

### PR DESCRIPTION
**Pull request by LEARNER1432**

### CODE REVIEW

**Comment by LEARNER1432** [comment]
Hactoberfest23

**Comment by yashjawale** [comment]
Please rename the file as ```Password Generator.py```

**Comment by yashjawale** [comment]
The file extension is incorrect

**Comment by yashjawale** [comment]
Change the name of the file then commit & push
It'll show up in this PR automatically

**Review by yashjawale — CHANGES_REQUESTED** [review]
Update **filename**

**Review by yashjawale — APPROVED** [review]

**Pull request merged**
