### PR TITLE
Addition to Data-structures and algorithm

### PR DESCRIPTION
**Pull request by NishantK30**
This is implementation of Binary search tree in python.

### CODE REVIEW

**Comment by yashjawale** [comment]
Typo in filename

**Comment by yashjawale** [comment]
Rename the file. 
Then Commit -> Push
It'll update here automatically

**Comment by yashjawale** [comment]
Let me know if facing any issues

**Comment by NishantK30** [comment]
Hey,
Thanks for pointing it out. Silly mistake 😅. I changed it now. Can you
confirm it's alright and get back to me?

**Comment by yashjawale** [comment]
Done 👍

**Pull request merged**
